name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go latest
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18

    - name: Short test
      run: go test -short -v ./...

    - name: Randomized test suite 1
      run: go test -v ./... -run RandomizeFast -count=512

    - name: Randomized test suite 2
      run: go test -v ./... -run RandomizeSlow -count=32

  test-old:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.15
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Short test
        run: go test -short -v ./...

      - name: Randomized test suite 1
        run: go test -v ./... -run RandomizeFast -count=512

      - name: Randomized test suite 2
        run: go test -v ./... -run RandomizeSlow -count=32